Apps/home/urls.py
from django.contrib import admin
from django.urls import path,include
from Apps.home import views     
from .views import HomeView,EstudiantesView,AdministradoresView,CrearAlumnoPublicaView,CrearAlumnoAutorizaViews,NoticiaViews,PublicacionView,ComentarioView
from .views import vnoticiasView,vpublicacionView,vcomentarioView,RegistroView,LoginView
from .views import ListarEstudianteView,ListarEstudianteAutorizaView,ListarNoticiaView,ListarPublicacionView,ListarComentarioView,EditarAlumnoPublicaView,EditarAlumnoAutorizaViews
from .views import EditarnoticiasView,EditarpublicacionView,EditarcomentarioView,EstudianteDetailView,EstudianteAutorizaDetailView
from .views import NoticiasDetailView,PublicacionDetailView,ComentarioDetailView
app_name='home'

urlpatterns = [
      path('', HomeView.as_view(), name='homeapp'),
      path('estudiantes/', EstudiantesView.as_view(), name='estudiantesapp'),
      path('administradores/', AdministradoresView.as_view(), name='administradoresapp'),
      path('crearEstudiante/', CrearAlumnoPublicaView.as_view(), name='CrearEstudiante'),
      path('crearEstudiantePublica/', CrearAlumnoAutorizaViews.as_view(), name='CrearEstudiantePublica'),
      path('Noticia/', NoticiaViews.as_view(), name='Noticiaapp'),  
      path('Publicacion/', PublicacionView.as_view(), name='Publicacionapp'),   
      path('Comentario/', ComentarioView.as_view(), name='Comentarioapp'),    
      path('CrearNoticia/', vnoticiasView.as_view(), name='CrearNoticia'),   
      path('CrearPublicacion/', vpublicacionView.as_view(), name='CrearPublicacion'),  
      path('CrearComentario/', vcomentarioView.as_view(), name='CrearComentario'),  
       path('registro/', RegistroView.as_view(), name='Registro'), 
       path('login/', LoginView.as_view(), name='login'),     
        path('listado_estudiante/', ListarEstudianteView.as_view(), name='listadoest'), 
        path('listado_estudianteAutoriza/', ListarEstudianteAutorizaView.as_view(), name='listadoestAuto'),    
        path('listado_noticia/', ListarNoticiaView.as_view(), name='listadonoticia'),    
        path('listado_publicacion/', ListarPublicacionView.as_view(), name='listadopublicacion'),   
        path('listado_comentario/', ListarComentarioView.as_view(), name='listadocomentario'), 
         path('editar_estudiante/<int:pk>', EditarAlumnoPublicaView.as_view(), name='editarest'),  
         path('editar_estudianteAutoriza/<int:pk>', EditarAlumnoAutorizaViews.as_view(), name='editarestAuto'),  
         path('editar_noticia/<int:pk>', EditarnoticiasView.as_view(), name='editarNoticia'),  
         path('editar_publicacion/<int:pk>', EditarpublicacionView.as_view(), name='editarPublicacion'),  
         path('editar_comentario/<int:pk>', EditarcomentarioView.as_view(), name='editarComentario'),  
           path('Estudiante_Detail/<int:pk>', EstudianteDetailView.as_view(), name='estudianteDet'),  
           path('EstudianteAutoriza_Detail/<int:pk>', EstudianteAutorizaDetailView.as_view(), name='estudianteAutoDet'),  
           path('Noticia_Detail/<int:pk>', NoticiasDetailView.as_view(), name='noticiaDet'),
           path('Publicacion_Detail/<int:pk>', PublicacionDetailView.as_view(), name='publicacionDet'),
           path('Comentario_Detail/<int:pk>', ComentarioDetailView.as_view(), name='comentarioDet'),
]          

ColegioSanJose/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Apps/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    Carne = models.CharField(max_length=100)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s %s' % (self.nombre,self.apellido,self.Carne)

class EstudianteAutoriza(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    Carne = models.CharField(max_length=15)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s %s' % (self.nombre,self.apellido,self.Carne)


class Noticias(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s ' % (self.nombre,self.descripcion)

class Publicacion(models.Model):
    numero = models.CharField(max_length=100)
    noticia = models.ForeignKey(Noticias,on_delete=models.CASCADE)
    estudiantepublica = models.ForeignKey(Estudiante,on_delete=models.CASCADE)
    estudianteautoriza = models.ForeignKey(EstudianteAutoriza,on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s %s %s' % (self.numero,self.noticia,self.estudiantepublica,self.estudianteautoriza)

class Comentario(models.Model):
    noticia = models.ForeignKey(Noticias,on_delete=models.CASCADE)
    Descripcion = models.CharField(max_length=100)
    estudiantepublica = models.ForeignKey(Estudiante,on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s %s ' % (self.noticia,self.Descripcion,self.estudiantepublica)

class Usuario(models.Model):
    perfil = models.OneToOneField(User,on_delete=models.CASCADE)    

    def __str__(self):
        return self.perfil.username

    @receiver(post_save, sender=User)
    def crear_usuario(sender, instance, created, **kwargs):
            if created:
                Usuario.objects.create(perfil=instance)

    @receiver(post_save, sender=User)
    def guardar_usuario(sender, instance, created, **kwargs):
             instance.usuario.save()

Apps/home/forms.py
from django import forms
from .models import Estudiante
from .models import EstudianteAutoriza
from .models import Noticias
from .models import Comentario
from .models import Publicacion
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class AlumnoPublicaForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__' 

class AlumnoAutorizaForm(forms.ModelForm):
    class Meta:
        model = EstudianteAutoriza
        fields = '__all__' 

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__' 

class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = '__all__' 

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticias
        fields = '__all__' 

class RegistroForm(UserCreationForm):
    first_name = forms.CharField(max_length=140,required=True)
    last_name = forms.CharField(max_length =140, required=False)
    email = forms.EmailField(required=True)       
    
    class Meta:
        model = User
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name', 
                  'password1',
                  'password2', 
        )

Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, UpdateView
from .forms import AlumnoPublicaForm, RegistroForm
from .forms import AlumnoAutorizaForm
from .forms import ComentarioForm
from .forms import NoticiaForm
from .forms import PublicacionForm
from .models import Usuario, Estudiante, EstudianteAutoriza, Noticias,Publicacion,Comentario
from django.contrib.auth.views import LoginView
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy
# Create your views here.

class HomeView(TemplateView):
     template_name='Home.html'

class EstudiantesView(TemplateView):
     template_name='estudiantes.html'

class AdministradoresView(TemplateView):
     template_name='administradores.html'   

class NoticiaViews(TemplateView):
     template_name='noticias.html'         

class PublicacionView(TemplateView):
     template_name='publicacion.html'  

class ComentarioView(TemplateView):
     template_name='comentario.html'       

class CrearAlumnoPublicaView(CreateView):
     template_name= 'alumnopublica.html'
     form_class = AlumnoPublicaForm
     success_url = reverse_lazy('home:listadoest')

class CrearAlumnoAutorizaViews(CreateView):
     template_name= 'Alumnoautoriza.html'
     form_class = AlumnoAutorizaForm
     success_url = reverse_lazy('home:listadoestAuto')

class vnoticiasView(CreateView):
     template_name= 'vnoticia.html'
     form_class = NoticiaForm
     success_url = reverse_lazy('home:listadonoticia')

class vpublicacionView(CreateView):
     template_name= 'vpublicacion.html'
     form_class = PublicacionForm
     success_url = reverse_lazy('home:listadopublicacion')

class vcomentarioView(CreateView):
     template_name= 'vcomentario.html'
     form_class = ComentarioForm
     success_url = reverse_lazy('home:listadocomentario')     

class RegistroView(CreateView):
     model = Usuario
     form_class = RegistroForm
     success_url = reverse_lazy('home:homeapp')    

class LoginView(LoginView):
     template_name = 'login.html'
    

class ListarEstudianteView(ListView):
     template_name = 'listarestudiante.html'
     model = Estudiante

     def get_queryset(self):
         bNombre = self.request.GET.get('nombre')
         if(bNombre):
             return Estudiante.objects.filter(nombre__icontains=bNombre)
         else:
             return Estudiante.objects.all()

class ListarEstudianteAutorizaView(ListView):
     template_name = 'listarestudianteautoriza.html'
     model = EstudianteAutoriza

     def get_queryset(self):
         aNombre = self.request.GET.get('nombre')
         if(aNombre):
             return EstudianteAutoriza.objects.filter(nombre__icontains=aNombre)
         else:
             return EstudianteAutoriza.objects.all()

class ListarNoticiaView(ListView):
     template_name = 'listarnoticia.html'
     model = Noticias

     def get_queryset(self):
         nNombre = self.request.GET.get('nombre')
         if(nNombre):
             return Noticias.objects.filter(nombre__icontains=nNombre)
         else:
             return Noticias.objects.all()


class ListarPublicacionView(ListView):
     template_name = 'listarpublicacion.html'
     model = Publicacion

     def get_queryset(self):

          pNoticia = self.request.GET.get('noticia')
          if(pNoticia):
             return Publicacion.objects.filter(noticia__descripcion__icontains=pNoticia)
          else:
             return Publicacion.objects.all()

class ListarComentarioView(ListView):
     template_name = 'listarcomentario.html'
     model = Comentario

     def get_queryset(self):
          bNoticia = self.request.GET.get('noticia')
          if(bNoticia):
             return Comentario.objects.filter(noticia__descripcion__icontains=bNoticia)
          else:
              return Comentario.objects.all()

class EditarAlumnoPublicaView(UpdateView):
     template_name= 'editaralumnopublica.html'
     model = Estudiante
     form_class = AlumnoPublicaForm
     success_url = reverse_lazy('home:listadoest')

class EditarAlumnoAutorizaViews(UpdateView):
     template_name= 'editaralumnoautoriza.html'
     model = EstudianteAutoriza
     form_class = AlumnoAutorizaForm
     success_url = reverse_lazy('home:listadoestAuto')

class EditarnoticiasView(UpdateView):
     template_name= 'editarnoticia.html'
     model = Noticias 
     form_class = NoticiaForm
     success_url = reverse_lazy('home:listadonoticia')

class EditarpublicacionView(UpdateView):
     template_name= 'editarpublicacion.html'
     model = Publicacion
     form_class = PublicacionForm
     success_url = reverse_lazy('home:listadopublicacion')

class EditarcomentarioView(UpdateView):
     template_name= 'editarcomentario.html'
     model = Comentario
     form_class = ComentarioForm
     success_url = reverse_lazy('home:listadocomentario')    

class EstudianteDetailView(DetailView):
     template_name= 'Estudiante_detail.html'
     model = Estudiante
     queryset = Estudiante.objects.all()

class EstudianteAutorizaDetailView(DetailView):
     template_name= 'Estudianteautoriza_detail.html'
     model = EstudianteAutoriza
     queryset = EstudianteAutoriza.objects.all()

class NoticiasDetailView(DetailView):
     template_name= 'noticia_detail.html'
     model = Noticias
     queryset = Noticias.objects.all()

class PublicacionDetailView(DetailView):
     template_name= 'publicacion_detail.html'
     model = Publicacion
     queryset = Publicacion.objects.all()

class ComentarioDetailView(DetailView):
     template_name= 'comentario_detail.html'
     model = Comentario
     queryset = Comentario.objects.all()

Apps/home/templates/Estudiante_detail.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
     
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
<div class="container" id="tablaalumn">
    <div class="row">
        <div class="col">
            <table class="table table-success table-striped">
                <td><strong>NOMBRE</strong></td>
                <td><strong>APELLIDO</strong></td>
                <td><strong>CARNE</strong></td>
                <td><strong>CREACION</strong></td>

                </tr>
                 
                <tr>
                    <td>
                        {{ object.nombre }}
                    </td>
                    <td>
                        {{ object.apellido }}
                    </td>
                    <td>
                        {{ object.Carne }}
                    </td>
                    <td>
                        {{ object.creacion }}
                    </td>

                    <td>
                        
                    </td>
                    
                </tr>
    

{% endblock %}
       

Apps/home/templates/Estudianteautoriza_detail.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
     
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
<div class="container" id="tablaalumn">
    <div class="row">
        <div class="col">
            <table class="table table-success table-striped">
                <td><strong>NOMBRE</strong></td>
                <td><strong>APELLIDO</strong></td>
                <td><strong>CARNE</strong></td>
                <td><strong>CREACION</strong></td>

                </tr>
                 
                <tr>
                    <td>
                        {{ object.nombre }}
                    </td>
                    <td>
                        {{ object.apellido }}
                    </td>
                    <td>
                        {{ object.Carne }}
                    </td>
                    <td>
                        {{ object.creacion }}
                    </td>

                    <td>
                        
                    </td>
                    
                </tr>
    

{% endblock %}
        

Apps/home/templates/administradores.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
    <!-- Header Start -->
    <div class="container-fluid bg-primary mb-5">
      <div
        class="d-flex flex-column align-items-center justify-content-center"
        style="min-height: 400px"
      >
        <h3 class="display-3 font-weight-bold text-white">ESTUDIANTE AUTORIZA</h3>
        <div class="d-inline-flex text-white">
         <!--  <p class="m-0"><a class="text-white" href="Index.html">Home</a></p> -->
           
          
        </div>
        
      </div>
    </div>
    <div  class="container"   id="tablaalumn" >
    <center>
      <h2> Crear Alumno que Autoriza </h2>
      <button type="button" class="btn btn-warning"><a href="{% url 'home:CrearEstudiantePublica' %}">Crear  </a></button>
      <button type="button" class="btn btn-warning"><a href="{% url 'home:listadoestAuto' %}">Listar Estudiantes Administradores </a></button>
       
    </center>
     
    </div>

    <!-- Header End -->

        
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}

Apps/home/templates/alumnoautoriza.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
    <h3 class="display-3 font-weight-bold text-white">ESTUDIANTES</h3>
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
      
    </div>
  </div>
</div>
<div  class="container"   id="tablaalumn" >
  <center>
  <h2> Crear Alumno que Autoriza </h2>
 <form method="POST">
    {% csrf_token %}
    Nombre {{form.nombre}}
    Apellido {{form.apellido}}
    Carné {{form.Carne}}
    <input type="submit" name="Guardar">
  </center>
 </form>
</div>
</div>
</div>
 <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
--> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}

Apps/home/templates/editarcomentario.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
    <h3 class="display-3 font-weight-bold text-white">EDITAR COMENTARIO</h3>
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
      
    </div>
  </div>
</div>
<div  class="container"   id="tablaalumn" >
    
  
 <form method="POST">
    {% csrf_token %}
    Noticia {{form.noticia}}
    Descripción {{form.Descripcion}}
    EstudiantePublica {{form.estudiantepublica}}
    
    <input type="submit" name="Guardar">
 </form>
</div>
</div>
</div>
 <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
--> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}

Apps/home/templates/editarnoticia.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
    <h3 class="display-3 font-weight-bold text-white">CREAR NOTICIA</h3>
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
      
    </div>
  </div>
</div>
<div  class="container"   id="tablaalumn" >
    <center>
  <h2> Crear Noticia </h2>
 <form method="POST">
    {% csrf_token %}
    Nombre {{form.nombre}}
    Descripcion {{form.descripcion}}
    
    <input type="submit" name="Guardar">
  </center>
 </form>
</div>
</div>
</div>
 <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
--> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}

Apps/home/templates/home.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
    <!-- Header Start -->
    <div class="container-fluid bg-primary px-0 px-md-5 mb-5">
        <div class="row align-items-center px-3">
          <div class="col-lg-6 text-center text-lg-left">
            <h1 class="display-3 font-weight-bold text-white">
              BIENVENIDOS
            </h1>
            <p class="text-white mb-4">
              En la siguiente pagina encontraran <br>
          toda la informacion relacionada sobre los<br> 
          alumnos y administradores del Colegio <br>
          San José.
            </p>
            <a href="" class="btn btn-secondary mt-1 py-3 px-5">Learn More</a>
          </div>
          <div class="col-lg-6 text-center text-lg-right">
            <img class="img-fluid mt-5" src="{% static 'img/header.png'%}" alt="" />    
          </div>
        </div>
      </div>
      <!-- Header End -->
   
    {% endblock %}

Apps/home/templates/listarcomentario.html
{% extends 'base.html'%}
{% block contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Listado de Comentarios</h3>
        <div class="d-inline-flex text-white">
            <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>-->


        </div>
    </div>
</div>

<div class="container" id="tablaalumn">
    <div class="row">
        <div class="col">
            <table class="table table-success table-striped">
                <center>
             <form action="" method="GET">
                <input type="text" name="noticia" value="{{request.GET.noticia}}">
                <button type="submit">BUSCAR</button>
            </center>
             </form>   
                <td><strong>NOTICIA</strong></td>
                <td><strong>DESCRIPCION</strong></td>
                <td><strong>ESTUDIANTE PUBLICA</strong></td>
                <td><strong>Acciones</strong></td>

                </tr>
                {% for est in object_list %}
                <tr>
                    <td>
                        {{ est.noticia }}
                    </td>
                    <td>
                        {{ est.descripcion }}
                    </td>
                    <td>
                        {{ est.estudiantepublica }}
                    </td>
                    <td>
                        <a href="{% url 'home:editarComentario' est.id %}"class="btn btn-warning">Editar </a>
                        <a href="{% url 'home:comentarioDet' est.id %}"class="btn btn-warning">Ver </a>
                    </td>
                </tr>
    
                {% endfor %}
            </table>
                <center>
            <button type="button" class="btn btn-warning"><a href="{% url 'home:Comentarioapp' %}">Regresar </a></button>
        </center>   
        </div>

        <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
        {% endblock %}

Apps/home/templates/listarnoticia.html
{% extends 'base.html'%}
{% block contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Listado de Noticias</h3>
        <div class="d-inline-flex text-white">
            <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>-->


        </div>
    </div>
</div>

<div class="container" id="tablaalumn">
    <div class="row">
        <div class="col">
            <table class="table table-success table-striped">
                <center>
                    <form action="" method="GET">
                        <input type="text" name="nombre" value="{{request.GET.nombre}}">
                        <button type="submit">BUSCAR</button>
                    </center>
                <td><strong>NOMBRE</strong></td>
                <td><strong>DESCRIPCION</strong></td>
                <td><strong>Acciones</strong></td>

                </tr>
                {% for est in object_list %}
                <tr>
                    <td>
                        {{ est.nombre }}
                    </td>
                    <td>
                        {{ est.descripcion }}
                    </td>
                    <td>
                        <a href="{% url 'home:editarNoticia' est.id %}"class="btn btn-warning">Editar </a>
                        <a href="{% url 'home:noticiaDet' est.id %}"class="btn btn-warning">Ver </a>
                    </td>
                </tr>
    
                {% endfor %}
            </table>
                <center>
            <button type="button" class="btn btn-warning"><a href="{% url 'home:Noticiaapp' %}">Regresar </a></button>
        </center>   
        </div>

        <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
        {% endblock %}

Apps/home/templates/login.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %} 
<body>
    

<center > 
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="submit">
    </form>
</center>
</body>
{% endblock %}

Apps/home/templates/noticias.html
{% extends 'base.html'%}
{% block  contenido %}
{% load static %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
  <div
    class="d-flex flex-column align-items-center justify-content-center"
    style="min-height: 400px"
  >
    <h3 class="display-3 font-weight-bold text-white">NOTICIAS</h3>
    <div class="d-inline-flex text-white">
     <!-- <p class="m-0"><a class="text-white" href="Index.html">Home</a></p>--> 
       
      
    </div>
  </div>
</div>
<div  class="container"   id="tablaalumn" >
    <center> 
  <h2> Crear Noticia </h2>
  <button type="button" class="btn btn-warning"><a href="{% url 'home:CrearNoticia' %}">Crear  </a></button>
      <button type="button" class="btn btn-warning"><a href="{% url 'home:listadonoticia' %}">Listar Noticias </a></button>
    </center>
</div>
</div>
</div>
 <!--  
<center>
<button id="btnagregaralum" class="boton" >Agregar</button>
<button id="btnListaralum" class="boton" > Listar</button>
</center>
--> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}